language: node_js
node_js:
  - node

branches:
  only:
    - master

before_script:
  - npm install --silent

script:
  - npm run test

after_success:
  - npm run deploy

notifications:
  email:
    on_failure: change
    on_success: change
